services:
  db:
    image: postgres:16
    container_name: bd_api_tareas
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_tareas_migrate
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    command: alembic upgrade head
    volumes:
      - ./backend:/app
    restart: "no"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-tareas
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_api_tareas
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_api_tareas
    ports:
      - "8080:80"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: