"""crear tablas estados y prioridades y FKs en tareas

Revision ID: f806adb83bc8
Revises: 574c48acb1b5
Create Date: 2026-03-05 13:37:43.756507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f806adb83bc8'
down_revision: Union[str, Sequence[str], None] = '574c48acb1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_id'), 'estados', ['id'], unique=True)
    op.create_index(op.f('ix_estados_nombre'), 'estados', ['nombre'], unique=True)
    op.create_table('prioridades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prioridades_id'), 'prioridades', ['id'], unique=True)
    op.create_index(op.f('ix_prioridades_nombre'), 'prioridades', ['nombre'], unique=True)
    op.add_column('tareas', sa.Column('titulo', sa.String(length=100), nullable=False))
    op.add_column('tareas', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('tareas', sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tareas', sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tareas', sa.Column('prioridad_id', sa.UUID(), nullable=False))
    op.add_column('tareas', sa.Column('estado_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_tareas_estado_id'), 'tareas', ['estado_id'], unique=False)
    op.create_index(op.f('ix_tareas_id'), 'tareas', ['id'], unique=True)
    op.create_index(op.f('ix_tareas_prioridad_id'), 'tareas', ['prioridad_id'], unique=False)
    op.create_index(op.f('ix_tareas_titulo'), 'tareas', ['titulo'], unique=False)
    op.create_foreign_key(None, 'tareas', 'estados', ['estado_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'tareas', 'prioridades', ['prioridad_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('tareas', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.drop_index(op.f('ix_tareas_titulo'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_prioridad_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_estado_id'), table_name='tareas')
    op.drop_column('tareas', 'estado_id')
    op.drop_column('tareas', 'prioridad_id')
    op.drop_column('tareas', 'fecha_modificacion')
    op.drop_column('tareas', 'fecha_creacion')
    op.drop_column('tareas', 'descripcion')
    op.drop_column('tareas', 'titulo')
    op.drop_index(op.f('ix_prioridades_nombre'), table_name='prioridades')
    op.drop_index(op.f('ix_prioridades_id'), table_name='prioridades')
    op.drop_table('prioridades')
    op.drop_index(op.f('ix_estados_nombre'), table_name='estados')
    op.drop_index(op.f('ix_estados_id'), table_name='estados')
    op.drop_table('estados')
    # ### end Alembic commands ###
